### PR TITLE
Possible typo fix

### PR DESCRIPTION
**Pull request by tinesife94**

### CODE REVIEW

**Comment by FranciscoPombal** [comment]
https://www.bittorrent.org/beps/bep_0014.html

>Local Service Discovery (LSD) provides a SSDP-like (http over udp-multicast) mechanism to announce the presence in specific swarms to local neighbors.
>
>It can be used either as primary peer source for local transfers or to complement other sources which only operate on global unicast addresses.

Thanks for the PR, but it's not really a typo. It's a historical artifact - everyone expands LSD ("local service discovery") as "local peer discovery". Not exactly sure why. @arvidn do you happen to know the reason?

**Comment by arvidn** [comment]
> Thanks for the PR, but it's not really a typo. It's a historical artifact - everyone expands LSD ("local service discovery") as "local peer discovery". Not exactly sure why. @arvidn do you happen to know the reason?

Well, I'd say when this was first implemented in uTorrent, it was called local service discovery (in lsd.cpp) by @ghazel. Maybe as a pun, who knows. At the time it was also called local peer discovery. So, anyway, it has two names. There's a swedish saying: "a dear child has many names".

**Comment by tinesife94** [comment]
Oh, I didn't know, sorry. Anyway, thanks for the nice info. Keep the good work.

**Comment by Chocobo1** [comment]
I suppose it is safe to close this.

**Pull request closed without merging**
