### PR TITLE
Convert index page to markdown format

### PR DESCRIPTION
**Pull request by Chocobo1**
* Convert index page to markdown format
* Update information in index.md
* Clean up footer

### CODE REVIEW

**Comment by sledgehammer999** [comment]
But why? (markdown)

**Comment by sledgehammer999** [comment]
@Chocobo1 sorry for hijacking this. I don't think I have your email address. Can you email me at sledgehammer999 (at) qbittorrent (dot) com? I want to share with you some webui security issues.

**Comment by Chocobo1** [comment]
>But why? (markdown)

I found the page is relatively easy to convert also markdown is easier for writing/modifying.

**Comment by Chocobo1** [comment]
>sledgehammer999 (at) qbittorrent (dot) com? 

**.com**? this reply sounds fishy, hope it's a typo.

**Comment by sledgehammer999** [comment]
>.com? this reply sounds fishy, hope it's a typo.

Sorry. You're right. It is .org.

**Pull request merged**
