### PR TITLE
Use lossless banner

### PR DESCRIPTION
**Pull request by adem4ik**
The existing banner is overcompressed, so it has a lot of artficats and it doesn't look good on the front page. I've decided to make it less compressed using the old png-file. File size has been increased too from 27 KiB to 60 KiB. Here is the comparison in 200% zoom (existing vs new):
comparison

### CODE REVIEW

**Comment by adem4ik** [comment]
@Chocobo1 Sure, I can make one by replacing qb_newbanner.png. Should I make a new PR or update this one?

**Comment by adem4ik** [comment]
@Chocobo1 I can rename old **qb_newbanner.png** to **qb_oldbanner.png** and add new **qb_newbanner.png**. Is if fine?

**Comment by Chocobo1** [comment]
>@Chocobo1 I can rename old qb_newbanner.png to qb_oldbanner.png and add new qb_newbanner.png. Is if fine?

OK.

**Comment by adem4ik** [comment]
I have no idea how to remove commits or squash them.

**Comment by Chocobo1** [comment]
It can be done in console:
```bash
git rebase -i HEAD~4
# mark commits as fixup or remove commit
```
Or I can help you do it, if you don't mind.

**Comment by sledgehammer999** [comment]
FYI, I am ok with the change. You can merge it when you fix the commit issue.

**Comment by adem4ik** [comment]
I've removed all the previous commits, added a new one according to the suggestions.

**Comment by Chocobo1** [comment]
Thank you!

... some how after pressing the merge button I suddenly remember it is possible to further compress the png with tools like PNGGauntlet... I will make a follow up commit.

**Pull request merged**
