### PR TITLE
v4.4.3 release month info fix

### PR DESCRIPTION
**Pull request by MuhammetEminCakir**

### CODE REVIEW

**Comment by summerqB** [comment]
Seems like there's a leftover line on line number 7 as well.

**Comment by MuhammetEminCakir** [comment]
> 7 numaralı satırda da kalan bir satır var gibi görünüyor.

I don't understand what they mean. So, i can't fix it. 
Pull requests welcome. @sledgehammer999

**Comment by MuhammetEminCakir** [comment]
> Seems like there's a leftover line on line number 7 as well.

I don't understand what they mean. So, i can't fix it.
Pull requests welcome. @sledgehammer999

**Comment by Chocobo1** [comment]
Already resolved now, thanks for the effort.

**Pull request closed without merging**
