### PR TITLE
Simplify the design of the latest version tag

### PR DESCRIPTION
**Pull request by eraychumak**
I would like to slowly contribute to modernizing the website with **small incremental changes** that are **easy to follow** and require **minimal effort to review** from the maintainers as time is important.

**EDIT:** As suggested, added a few more screenshots to showcase the visual changes on different screen sizes.

## Visual changes

| Before      | After |
| ----------- | ----------- |
| image | image |
| image | image |
| image | image |

### CODE REVIEW

**Comment by eraychumak** [comment]
Wanted to double check if anyone has seen this PR?

**Comment by Chocobo1** [comment]
I don't strongly favor the new design so I'll leave it for other maintainers to decide.

**Comment by eraychumak** [comment]
Bump _(I apologise in-case this is not allowed)_

**Comment by PriitUring** [comment]
@eraychumak

If you want to propose website design changes, then you should recheck how your changes look on various display resolutions, including mobile devices.

Without providing more than 1 comparison, then it's hard for others to quickly decline or approve even a simple change.

**Comment by eraychumak** [comment]
> @eraychumak
> 
> If you want to propose website design changes, then you should recheck how your changes look on various display resolutions, including mobile devices.
> 
> Without providing more than 1 comparison, then it's hard for others to quickly decline or approve even a simple change.

Thanks for the tip @PriitUring, I've updated the PR to include more screenshots and will do from now on. Hope that helps 👍

**Comment by eraychumak** [comment]
Resetting with a new fork for a later PR in the future maybe👍 _sorry_

**Pull request closed without merging**
