### PR TITLE
Minor tweaks to layout

### PR DESCRIPTION
**Pull request by Poopooracoocoo**
Now uses CSS instead of images, uses `max-width` instead of `width`, and changed max width to 920px from 800px (which is a nicer width IMO). :)

note that i'm a total noob and that i *attempted* to test it.

<details><summary>Screenshots, just after editing through dev tools</summary>

before
image

after
image

Not mobile, that'd require some more work! But this shows you that it's better :

before
image

after
image

after: rev 2, because the ribbon's span blocks input >:(
image

after: if banner.png is cropped to 600px
image

</details>

### CODE REVIEW

**Comment by Poopooracoocoo** [comment]
@Chocobo1 Hey Mike. What are your thoughts on this PR and on the issue I opened? :) 

how did you losslessly compress the header image by the way? it would be nice if it were 600px! I tried cropping it but the size became bigger somehow.

sorry about all the commits.
just pinging in case you didn't receive a notification

**Comment by Chocobo1** [comment]
>Hey Mike. What are your thoughts on this PR and on the issue I opened? :)

I haven't got time to look at it. Let me know when you think it is ready.

**Comment by Poopooracoocoo** [comment]
i reckon it's ready! :P if i have any more changes i might open a new PR.

**Comment by Chocobo1** [comment]
@Poopooracoocoo 
Thank you!

**Comment by Poopooracoocoo** [comment]
@Chocobo1 
Thank you sooo much! And thanks for cleaning up the CSS! 

Did you use a tool to sort it? And how did you compress the banner image? I'd like to crop the banner so it looks better on phones, although it's not necessary.

**Comment by Chocobo1** [comment]
>Did you use a tool to sort it?

I found some css formatter found on the net and manually handled the rest.

>And how did you compress the banner image? 

Zopflipng.

**Pull request merged**
