### PR TITLE
Website redesign proposal

### PR DESCRIPTION
**Pull request by merfire**
Website redesign proposal.
Homepage:
qbittorrent-homepage
Download:
qbittorrent-download
News:
qbittorrent-news
Team:
qbittorrent-team

### CODE REVIEW

**Comment by Chocobo1** [comment]
Cool! Looks clean and nice.

@sledgehammer999 
Any comments on visual?

**Comment by swat-web** [comment]
Isn't perfect, but looks way better then existing

**Comment by kerembeyazit** [comment]
Great design. Is it alive?

**Comment by cantalupo555** [comment]
@sledgehammer999 beautiful work

**Comment by kerembeyazit** [comment]
Let's make this project using webpack.

**Pull request closed without merging**
